import Link from 'next/link';

export default function TermsOfServicePage() {
  return (
    <div className="container mx-auto px-4 sm:px-6 py-8 sm:py-12 max-w-4xl">
      <header className="mb-8 sm:mb-12">
        <h1 className="text-3xl sm:text-4xl font-bold text-gray-900 mb-4">
          Terms of Service
        </h1>
        <p className="text-lg text-gray-600">
          Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
        </p>
      </header>

      <div className="prose prose-lg max-w-none">
        <section className="mb-8">
          <h2 className="text-2xl font-bold text-gray-900 mb-4">1. AI-Generated Content Disclosure</h2>
          <p className="text-gray-700 leading-relaxed mb-4">
            <strong>Important Notice:</strong> This website (vegancooking.recipes) is largely AI-generated. The recipes, 
            content, images, and other materials on this site are created with the assistance of artificial intelligence 
            technologies. While we strive to provide useful and accurate information, we cannot guarantee the accuracy, 
            completeness, or reliability of any content on this site.
          </p>
          <ul className="list-disc list-inside space-y-2 text-gray-700 mb-4">
            <li>
              <strong>AI-Generated Recipes:</strong> The recipes on this website are generated using AI technology. 
              They have not been tested, verified, or guaranteed for accuracy, taste, nutritional content, or safety.
            </li>
            <li>
              <strong>No Accuracy Guarantee:</strong> We make no representations or warranties regarding the accuracy, 
              reliability, or suitability of any recipe or content on this site. Recipes are provided &quot;as is&quot; 
              without any guarantee of results.
            </li>
            <li>
              <strong>Use at Your Own Risk:</strong> You acknowledge that you use all recipes and content at your own 
              risk. We are not responsible for any outcomes, including but not limited to food safety issues, allergic 
              reactions, or unsatisfactory results.
            </li>
            <li>
              <strong>Nutritional Information:</strong> Any nutritional information provided is calculated by AI and 
              may not be accurate. Always verify nutritional information if you have specific dietary requirements or 
              restrictions.
            </li>
            <li>
              <strong>Character Disclaimer:</strong> Noah, the character featured on this site, is an AI-generated 
              character loosely based on the developer of this site. All content attributed to Noah is AI-generated 
              and should not be considered as personal advice or recommendations from a real person.
            </li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold text-gray-900 mb-4">2. Recipe Veganization Service</h2>
          <p className="text-gray-700 leading-relaxed mb-4">
            By using our recipe veganization tool, you acknowledge and agree to the following terms:
          </p>
          <ul className="list-disc list-inside space-y-2 text-gray-700 mb-4">
            <li>
              <strong>AI-Powered Transformation:</strong> Our veganization tool uses artificial intelligence (AI) 
              to automatically transform non-vegan recipes into vegan versions. The AI analyzes the original recipe 
              and replaces non-vegan ingredients with plant-based alternatives.
            </li>
            <li>
              <strong>Automatic Publication:</strong> When you veganize a recipe using our tool, the veganized 
              version will be automatically saved and published to our website (vegancooking.recipes) as a new recipe. 
              This means the veganized recipe becomes publicly accessible to all visitors of our site.
            </li>
            <li>
              <strong>Recipe Ownership:</strong> By submitting a recipe URL for veganization, you grant us a 
              perpetual, non-exclusive, royalty-free license to use, display, and distribute the veganized recipe 
              on our website and through our services.
            </li>
            <li>
              <strong>No Original Recipe Rights:</strong> We do not claim ownership of the original recipe you provide. 
              The veganized version is a derivative work created by our AI system.
            </li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold text-gray-900 mb-4">3. Recipe Accuracy and Disclaimers</h2>
          <ul className="list-disc list-inside space-y-2 text-gray-700 mb-4">
            <li>
              <strong>AI-Generated Content:</strong> Veganized recipes are generated by AI and may require 
              human review and testing. We cannot guarantee the accuracy, taste, or nutritional content of 
              veganized recipes.
            </li>
            <li>
              <strong>Ingredient Substitutions:</strong> AI-generated ingredient substitutions are suggestions 
              based on common vegan alternatives. Results may vary, and you should use your judgment when 
              following veganized recipes.
            </li>
            <li>
              <strong>Nutritional Information:</strong> Nutritional information in veganized recipes is calculated 
              by AI and may not be 100% accurate. Always verify nutritional information if you have specific 
              dietary requirements.
            </li>
            <li>
              <strong>No Warranty:</strong> We provide the veganization service &quot;as is&quot; without warranties 
              of any kind, express or implied, including but not limited to accuracy, completeness, or fitness for 
              a particular purpose.
            </li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold text-gray-900 mb-4">4. User Responsibilities</h2>
          <ul className="list-disc list-inside space-y-2 text-gray-700 mb-4">
            <li>
              <strong>Recipe URLs:</strong> You are responsible for ensuring you have the right to submit recipes 
              from the URLs you provide. Do not submit recipes that are copyrighted or proprietary without 
              appropriate authorization.
            </li>
            <li>
              <strong>Content Review:</strong> We recommend reviewing veganized recipes before using them, 
              especially if you have food allergies or dietary restrictions.
            </li>
            <li>
              <strong>Attribution:</strong> While we do not require attribution for veganized recipes, we 
              appreciate when users acknowledge the original recipe source when sharing.
            </li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold text-gray-900 mb-4">5. Content Moderation</h2>
          <p className="text-gray-700 leading-relaxed mb-4">
            We reserve the right to:
          </p>
          <ul className="list-disc list-inside space-y-2 text-gray-700 mb-4">
            <li>Review, edit, or remove any veganized recipes from our website</li>
            <li>Refuse to veganize recipes that violate our content policies</li>
            <li>Block users who abuse the veganization service</li>
            <li>Improve or modify veganized recipes using AI or manual editing</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold text-gray-900 mb-4">6. Limitation of Liability</h2>
          <p className="text-gray-700 leading-relaxed mb-4">
            To the maximum extent permitted by law, vegancooking.recipes and its operators shall not be liable 
            for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or 
            revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other 
            intangible losses resulting from your use of the veganization service.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold text-gray-900 mb-4">7. Changes to Terms</h2>
          <p className="text-gray-700 leading-relaxed mb-4">
            We reserve the right to modify these Terms of Service at any time. Changes will be effective 
            immediately upon posting to this page. Your continued use of the veganization service after 
            changes are posted constitutes acceptance of the modified terms.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold text-gray-900 mb-4">8. Contact</h2>
          <p className="text-gray-700 leading-relaxed mb-4">
            If you have questions about these Terms of Service, please contact us through our{' '}
            <Link href="/contact" className="text-green-600 hover:text-green-700 underline">
              contact page
            </Link>.
          </p>
        </section>

        <div className="mt-12 pt-8 border-t border-gray-200">
          <div className="flex flex-col sm:flex-row gap-4">
            <Link 
              href="/"
              className="text-green-600 hover:text-green-700 underline font-medium"
            >
              ← Back to Home
            </Link>
            <Link 
              href="/veganize" 
              className="text-green-600 hover:text-green-700 underline font-medium"
            >
              Veganize Tool
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}
